name: Docker and S3 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t devops-task .       
      - name: Copy Files from Container
        run: |
          docker create --name devops-task devops-task
          docker cp devops-task:/app/.open-next/ ./out
      - name: List Files in Out Directory
        run: ls -l ./out
      - name: Upload Extracted Files as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracted-files
          path: ./out/

  package:
    name: Package Subfolders
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Extracted Files
        uses: actions/download-artifact@v3
        with:
          name: extracted-files

      - name: Install Zip Utility
        run: sudo apt-get install -y zip
      - name: check folder
        run: ls -la
      - name: Zip Subfolders
        run: |
          for dir in */; do
            zip -r "${dir%/}.zip" "$dir"
          done
          ls -la

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
     
      - name: Create S3 Bucket
        run: aws s3 mb s3://lambda --region us-east-1 || echo "Bucket already exists"
      
      - name: Upload Zips Listed in zip-files.txt
        run: |
          while IFS= read -r file; do
            aws s3 cp "./out/$file" "s3://lambda/$file"
          done < ./out/zip-files.txt        